### ISSUE TITLE
Review Guided Interaction Field Mapping

### ISSUE THREAD

**Issue by renell-carpenter** [Ready-Ready/Prenatal_Navigation_PNP#2]
For each question: Who is the data about
And what type of data is being collected (what SF object the form is ultimately mapped to: Profile, Need, what else?

**Comment by renell-carpenter** [comment]
Need to include Screening questions as well -- map to Needs, Risks? what else?

**Comment by lconway-cc** [comment]
Transferred to TaskRay on 4/29
